// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	target "github.com/zenoss/zenoss-go-sdk/health/target"
)

// Destination is an autogenerated mock type for the Destination type
type Destination struct {
	mock.Mock
}

// Push provides a mock function with given fields: health
func (_m *Destination) Push(health *target.Health) error {
	ret := _m.Called(health)

	var r0 error
	if rf, ok := ret.Get(0).(func(*target.Health) error); ok {
		r0 = rf(health)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
