// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	component "github.com/zenoss/zenoss-go-sdk/health/component"
)

// Destination is an autogenerated mock type for the Destination type
type Destination struct {
	mock.Mock
}

// Push provides a mock function with given fields: ctx, health
func (_m *Destination) Push(ctx context.Context, health *component.Health) error {
	ret := _m.Called(ctx, health)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *component.Health) error); ok {
		r0 = rf(ctx, health)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Register provides a mock function with given fields: ctx, _a1
func (_m *Destination) Register(ctx context.Context, _a1 *component.Component) error {
	ret := _m.Called(ctx, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *component.Component) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
